version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: scripts/pullDocker.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/runDocker.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stopDocker.sh
      timeout: 60
      runas: ec2-user
