version: 0.1
phases:
  pre_build:
    commands:
      - 'echo Logging in to Docker Hub...'
      - 'docker login --username="ssunnu" --password="testtesttest"'
  build:
    commands:
      - 'echo Build started on `date`'
      - 'echo Building the Docker image...'
      - 'docker-compose -f docker-compose.yml build'
  post_build:
    commands:
      - 'echo Build completed on `date`'
      - 'echo Pushing the Docker image...'
      - 'docker-compose -f docker-compose.yml push'

artifacts:
  files:
    - 'appspec.yml'
    - 'scripts/*'
    - 'docker-compose.yml'
    - 'Dockerfile'
    - 'dist/*'
    - 'node_modules/*'
    - 'package.json'
    - 'package-lock.json'
    - 'buildspec.dev.yml'
    - 'nest-cli.json'
    - 'tsconfig.build.json'
    - 'tsconfig.json'
    - 'src/*'
