
version: "3"
services:
  app:
    restart: always
    image: helltabus # goes to your repository on Docker Hub
    build:
      dockerfile: Dockerfile.dev
      context: .
    container_name: "app"
    volumes:
      - node_modules:/app/node_modules
    ports:
      - "5000:5000"


  # db:
  #   image: 'mysql:5.7'
  #   ports:
  #     - 3309:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: hell_ta_bus
  #   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
